import { execSync } from 'child_process';

export function createImprovementBranch(scores) {
  const timestamp = new Date().toISOString().slice(0, 10);
  const branchName = `auto-improve/${timestamp}`;
  try {
    execSync(`git checkout -b ${branchName}`, { stdio: 'ignore' });
    log(`Created branch: ${branchName}`);
    return branchName;
  } catch (err) {
    log(`Failed to create branch: ${err.message}`, 'warn');
    return null;
  }
}

export function commitImprovements(scores) {
  const fr = (scores.avgFileRecall * 100).toFixed(1);
  const sr = (scores.avgSymbolRecall * 100).toFixed(1);
  const message = `auto-improve: file recall ${fr}%, symbol recall ${sr}%`;
  try {
    execSync('git add -A', { stdio: 'ignore' });
    execSync(`git commit -m "${message}"`, { stdio: 'ignore' });
    log(`Committed: ${message}`);
    return true;
  } catch (err) {
    log(`Commit failed: ${err.message}`, 'warn');
    return false;
  }
}

export function pushBranch(branchName) {
  try {
    execSync(`git push -u origin ${branchName}`, { stdio: 'ignore' });
    log(`Pushed: ${branchName}`);
    return true;
  } catch (err) {
    log(`Push failed: ${err.message}`, 'warn');
    return false;
  }
}

export function createPR(branchName, scores) {
  const fr = (scores.avgFileRecall * 100).toFixed(1);
  const sr = (scores.avgSymbolRecall * 100).toFixed(1);
  const body = `## Auto-improvement results\n\n- File recall: ${fr}%\n- Symbol recall: ${sr}%\n\nGenerated by geniesh self-improve.`;
  try {
    const url = execSync(
      `gh pr create --title "auto-improve: ${fr}% / ${sr}%" --body "${body}"`,
      { encoding: 'utf-8' }
    ).trim();
    log(`PR created: ${url}`);
    return url;
  } catch (err) {
    log(`PR creation failed: ${err.message}`, 'warn');
    return null;
  }
}

function log(msg, level = 'info') {
  const prefix = level === 'info' ? '  ' : '  ⚠';
  console.log(`${prefix} ${msg}`);
}
